"""add indexes improve alert model

Revision ID: 0638d2178d1f
Revises: 1d558ccbc42d
Create Date: 2026-03-14 12:42:03.229520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0638d2178d1f'
down_revision: Union[str, Sequence[str], None] = '1d558ccbc42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_corr_period_coin_a', 'analytics_correlation', ['period_days', 'coin_a_id'], unique=False)
    op.create_index('idx_corr_period_coin_b', 'analytics_correlation', ['period_days', 'coin_b_id'], unique=False)
    op.create_index(op.f('ix_data_quality_checks_executed_at'), 'data_quality_checks', ['executed_at'], unique=False)
    op.alter_column('price_alerts', 'target_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_user_coin_direction'), 'price_alerts', type_='unique')
    op.create_index('idx_alert_user_coin', 'price_alerts', ['user_id', 'coin_id'], unique=False)
    op.create_index(op.f('ix_price_alerts_coin_id'), 'price_alerts', ['coin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_alerts_coin_id'), table_name='price_alerts')
    op.drop_index('idx_alert_user_coin', table_name='price_alerts')
    op.create_unique_constraint(op.f('uq_user_coin_direction'), 'price_alerts', ['user_id', 'coin_id', 'direction'], postgresql_nulls_not_distinct=False)
    op.alter_column('price_alerts', 'target_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_index(op.f('ix_data_quality_checks_executed_at'), table_name='data_quality_checks')
    op.drop_index('idx_corr_period_coin_b', table_name='analytics_correlation')
    op.drop_index('idx_corr_period_coin_a', table_name='analytics_correlation')
    # ### end Alembic commands ###
