"""add_ath_atl_supply_fields_to_dim_coin

Revision ID: 1c04ca751424
Revises: c5a0f32289e1
Create Date: 2026-02-28 12:15:51.712089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c04ca751424'
down_revision: Union[str, Sequence[str], None] = 'c5a0f32289e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_coin', sa.Column('ath', sa.Numeric(), nullable=True))
    op.add_column('dim_coin', sa.Column('ath_date', sa.DateTime(), nullable=True))
    op.add_column('dim_coin', sa.Column('atl', sa.Numeric(), nullable=True))
    op.add_column('dim_coin', sa.Column('atl_date', sa.DateTime(), nullable=True))
    op.add_column('dim_coin', sa.Column('total_supply', sa.Numeric(), nullable=True))
    op.add_column('dim_coin', sa.Column('max_supply', sa.Numeric(), nullable=True))
    op.add_column('dim_coin', sa.Column('high_24h', sa.Numeric(), nullable=True))
    op.add_column('dim_coin', sa.Column('low_24h', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_coin', 'low_24h')
    op.drop_column('dim_coin', 'high_24h')
    op.drop_column('dim_coin', 'max_supply')
    op.drop_column('dim_coin', 'total_supply')
    op.drop_column('dim_coin', 'atl_date')
    op.drop_column('dim_coin', 'atl')
    op.drop_column('dim_coin', 'ath_date')
    op.drop_column('dim_coin', 'ath')
    # ### end Alembic commands ###
