"""initial schema

Revision ID: 650a7819bb0b
Revises: 
Create Date: 2026-02-13 12:17:05.519641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650a7819bb0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.String(length=200), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coingecko_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coingecko_id')
    )
    op.create_table('dim_time',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('week', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dag_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analytics_correlation',
    sa.Column('coin_a_id', sa.Integer(), nullable=False),
    sa.Column('coin_b_id', sa.Integer(), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('correlation', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin_a_id'], ['dim_coin.id'], ),
    sa.ForeignKeyConstraint(['coin_b_id'], ['dim_coin.id'], ),
    sa.PrimaryKeyConstraint('coin_a_id', 'coin_b_id', 'period_days')
    )
    op.create_table('analytics_volatility',
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('volatility', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['dim_coin.id'], ),
    sa.PrimaryKeyConstraint('coin_id', 'period_days')
    )
    op.create_table('fact_daily_ohlcv',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['dim_coin.id'], ),
    sa.ForeignKeyConstraint(['date'], ['dim_time.date'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_id', 'date', name='uq_ohlcv_coin_date')
    )
    op.create_table('fact_market_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('total_volume', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('price_change_24h_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('circulating_supply', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['dim_coin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_id', 'timestamp', name='uq_market_coin_ts')
    )
    op.create_index('idx_fact_market_coin_ts', 'fact_market_data', ['coin_id', 'timestamp'], unique=False)
    op.create_index('idx_fact_market_ts', 'fact_market_data', ['timestamp'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fact_market_ts', table_name='fact_market_data', postgresql_using='btree')
    op.drop_index('idx_fact_market_coin_ts', table_name='fact_market_data')
    op.drop_table('fact_market_data')
    op.drop_table('fact_daily_ohlcv')
    op.drop_table('analytics_volatility')
    op.drop_table('analytics_correlation')
    op.drop_table('users')
    op.drop_table('pipeline_runs')
    op.drop_table('dim_time')
    op.drop_table('dim_coin')
    op.drop_table('data_quality_checks')
    # ### end Alembic commands ###
