"""add_portfolio_holdings

Revision ID: c5a0f32289e1
Revises: f906206b051b
Create Date: 2026-02-15 22:55:09.092501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a0f32289e1'
down_revision: Union[str, Sequence[str], None] = 'f906206b051b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('buy_price_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['dim_coin.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_user', 'portfolio_holdings', ['user_id'], unique=False)
    op.create_index('idx_portfolio_user_coin', 'portfolio_holdings', ['user_id', 'coin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_portfolio_user_coin', table_name='portfolio_holdings')
    op.drop_index('idx_portfolio_user', table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    # ### end Alembic commands ###
